server:
  port: 8082

spring:
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true

  dubbo:
    application:
      name: dubbo-consumer
      id: dubbo-consumer
    #注册中心地址
    registry:
      address: zookeeper://127.0.0.1:2181
    #配置了这个后，就会一直有守护京城，而不是启动就怪盗了
    server:  true
    #扫描的包
    scan: com.qging.dubbo.consumer.controller
    # Dubbo Protocol
    protocol:
      name: dubbo
      port: 20880
